# coding: utf-8

"""
    Release Manager

    This application generate version for your software.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: vitalleshchyk@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import release-manager-client
from release-manager-client.api.version_semantic_api import VersionSemanticApi  # noqa: E501
from release-manager-client.rest import ApiException


class TestVersionSemanticApi(unittest.TestCase):
    """VersionSemanticApi unit test stubs"""

    def setUp(self):
        self.api = release-manager-client.api.version_semantic_api.VersionSemanticApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_semver_generate(self):
        """Test case for semver_generate

        Generate new semantic version number (based on gitflow)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
