# coding: utf-8

"""
    Release Manager

    This application generate version for your software.  # noqa: E501

    The version of the OpenAPI document: 0.2.0
    Contact: vitalleshchyk@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import release-manager-client
from release-manager-client.models.project import Project  # noqa: E501
from release-manager-client.rest import ApiException


class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProject(self):
        """Test Project"""
        # FIXME: construct object with mandatory attributes with example values
        # model = release-manager-client.models.project.Project()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
